llm_configs:
  general_configs:
    max_token_length: 24064
    temperature: 1
    top_p: 1
  qwen2.5-7b:
    model: "Qwen/Qwen2.5-7B-Instruct"
    model_path: null
  qwen2.5-math-7b:
    model: "Qwen/Qwen2.5-Math-7B-Instruct"
    model_path: null
    max_token_length: 4096
    temperature: 0.2
  qwq-32b:
    model: "Qwen/QWQ-32B-Instruct"
    model_path: null
  deepseek-math-7b:
    model: "deepseek-ai/deepseek-math-7b-instruct"
    model_path: null
    max_token_length: 4096